### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by PolymorphicAgent** [Xd-pro/opera-rich-presence#1]
DO NOT run main.exe from the release - IT IS A VIRUS!!!
virus total: 
[https://www.virustotal.com/gui/file/1340d1b05b27627b537e45927dde729ad66981f9b176f3a610e073c7232292a5/community](url)

**Comment by Xd-pro** [comment]
![image](https://github.com/Xd-pro/opera-rich-presence/assets/62808970/577b66ab-0658-4099-add6-80cfb2fe8cc1)
2/68

The issue `Trojan.PSW.Python.bm` seems to be caused by access to the browser.

This is not a virus according to 66 of the 68 antivirus programs on virustotal.
